[target_rhel]
target_host1
target_host2
target_host3 simulate_failure=true
target_host4

[target_ubuntu]
target_host5
target_host6

[target_hosts:children]
target_rhel
target_ubuntu

[target_hosts:vars]
ansible_user=root
ansible_port=22
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
